### ISSUE TITLE
Update readme please

### ISSUE THREAD

**Issue by daddydrac** [yankcrime/k2sup#1]
Please show how to install, also the "how to use" isnt clear to me. 

-  Do I need to deploy VMs first?
-  Where do I get these values from ->
    ```
       tls-san:
         - "192.168.20.200"
         - "rke2.192.168.20.200.dnsify.me"
     ```

**Comment by yankcrime** [comment]
Thanks for the feedback - done via https://github.com/yankcrime/k2sup/commit/ffc68a3108da195cd832246e07c9791e16c974b1
